/*
 * This source file was generated by the Gradle 'init' task
 */
package org.parmentier;

import org.junit.jupiter.api.Test;
import org.parmentier.level.*;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertEquals;

class LevelTest {
    @Test void NodeBridgeTest() {
        Node n1 = new Node(1, 2, 1);
        Node n2 = new Node(1, 0, 1);
        Bridge b1 = new Bridge(n1, n2, Bridge.Direction.TOP);
        b1.setState(1);
        b1.setSolutionState(1);
        n1.addBridge(b1);
        n2.addBridge(b1);

        assertEquals(0, n1.countErrors());
        assertTrue(n1.checkState());

        b1.setSolutionState(0);
        assertEquals(1, n1.countErrors());
        assertFalse(n1.checkState());
    }
    
}
